import 'main.dart';

List<TabuKart> devKelimeListesi = [
  TabuKart(anaKelime: "SANTRFOR", yasakliKelimeler: ["FUTBOL","OYUNCU","SAHA","FORVET","GOL"]),
  TabuKart(anaKelime: "MOZAİK", yasakliKelimeler: ["KÜÇÜK","TAŞ","PASTA","DUVAR","PARÇA"]),
  TabuKart(anaKelime: "SERTİFİKA", yasakliKelimeler: ["BELGE","ALMAK","VERMEK","EĞİTİM","KURS"]),
  TabuKart(anaKelime: "İNSAN SARRAFI", yasakliKelimeler: ["ANLAMAK","TANIMAK","İYİ","KÖTÜ","BİLMEK"]),
  TabuKart(anaKelime: "ELİ YATKIN", yasakliKelimeler: ["BECERİKLİ","HAMARAT","İŞ","BİLMEK","ÇALIŞMAK"]),
  TabuKart(anaKelime: "PİRAMİT", yasakliKelimeler: ["MISIR","ÜÇGEN","ŞEKİL","FİRAVUN","TAŞ"]),
  TabuKart(anaKelime: "FRENK ÜZÜMÜ", yasakliKelimeler: ["KIRMIZI","ŞURUP","BÖĞÜRTLEN","AHUDUDU","MEYVE"]),
  TabuKart(anaKelime: "MUTLU SON", yasakliKelimeler: ["HİKAYE","MASAL","FİLM","AŞK","BİTMEK"]),
  TabuKart(anaKelime: "İŞ KURMAK", yasakliKelimeler: ["DÜKKAN","AÇMAK","PATRON","KENDİ","ŞİRKET"]),
  TabuKart(anaKelime: "ÖZGÜVEN", yasakliKelimeler: ["SAYGI","KENDİ","İNANMAK","BAŞARMAK","EGO"]),
  TabuKart(anaKelime: "TİFTİK", yasakliKelimeler: ["KEÇİ","YÜN","KAZAK","YUMUŞAK","KIL"]),
  TabuKart(anaKelime: "ULVİ", yasakliKelimeler: ["AMAÇ","YÜKSEK","ULU","YÜCE","BENZERSİZ"]),
  TabuKart(anaKelime: "LAÇKALAŞMAK", yasakliKelimeler: ["GEVŞEMEK","RAHAT","SAMİMİ","ORTAM","ESKİMEK"]),
  TabuKart(anaKelime: "LARVA", yasakliKelimeler: ["KURTÇUK","KURBAĞA","SİNEK","YUMURTA","YAVRU"]),
  TabuKart(anaKelime: "KÖPEKBALIĞI", yasakliKelimeler: ["HAYVAN","YÜZGEÇ","JAWS","BALİNA","OKYANUS"]),
  TabuKart(anaKelime: "LIV TYLER", yasakliKelimeler: ["SİNEMA","OYUNCU","ARWEN","ARAGORN","ELF"]),
  TabuKart(anaKelime: "FİLETO", yasakliKelimeler: ["ET","KESMEK","İNCE","DİLİM","BALIK"]),
  TabuKart(anaKelime: "RANDIMAN", yasakliKelimeler: ["VERİM","ÇALIŞMAK","İŞ","SONUÇ","BAŞARI"]),
  TabuKart(anaKelime: "LAFAZAN", yasakliKelimeler: ["KONUŞMAK","GEVEZE","SÖZ","HAZIRCEVAP","ANLATMAK"]),
  TabuKart(anaKelime: "DERBEDER", yasakliKelimeler: ["DAĞINIK","TİTİZ","TEMİZ","YAŞAMAK","DÜZENSİZ"]),
  TabuKart(anaKelime: "MAT ETMEK", yasakliKelimeler: ["SATRANÇ","YENMEK","BİTİRMEK","ŞAH","ALT ETMEK"]),
  TabuKart(anaKelime: "ÇİĞ BÖREK", yasakliKelimeler: ["YİYECEK","HAMUR","KIZARTMAK","MANTI","PUF BÖREĞİ"]),
  TabuKart(anaKelime: "MESANE", yasakliKelimeler: ["ŞİŞMEK","İDRAR","TORBA","KESE","ÇİŞ"]),
  TabuKart(anaKelime: "SUDOKU", yasakliKelimeler: ["BULMACA","SAYI","YERLEŞTİRMEK","KARE","JAPONYA"]),
  TabuKart(anaKelime: "DİNAR", yasakliKelimeler: ["PARA","BİRİM","IRAK","ARAP","KUVEYT"]),
  TabuKart(anaKelime: "KALSİYUM", yasakliKelimeler: ["KEMİK","SÜT","PEYNİR","YOĞURT","DİŞ"]),
  TabuKart(anaKelime: "ORTODONTİ", yasakliKelimeler: ["DİŞ","TIP","DAL","TEL","DOKTOR"]),
  TabuKart(anaKelime: "KAĞIT HAVLU", yasakliKelimeler: ["SİLMEK","RULO","KURULAMAK","DÖKÜLMEK","MUTFAK"]),
  TabuKart(anaKelime: "AYNASIZ", yasakliKelimeler: ["POLİS","ARGO","HIRSIZ","FİLM","KOMİSER"]),
  TabuKart(anaKelime: "PROJEKTÖR", yasakliKelimeler: ["YANSITMAK","SİNEMA","SUNUM","IŞIK","PERDE"]),
  TabuKart(anaKelime: "ŞEHRAZAT", yasakliKelimeler: ["1001 GECE","MASAL","KAHRAMAN","ANLATMAK","BERGÜZAR KOREL"]),
  TabuKart(anaKelime: "EVHAM", yasakliKelimeler: ["PANİK","ŞÜPHE","KUŞKU","VESVESE","ENDİŞE"]),
  TabuKart(anaKelime: "PARMAKLIK", yasakliKelimeler: ["HAPİSHANE","HIRSIZ","PENCERE","DEMİR","TAKMAK"]),
  TabuKart(anaKelime: "İSHAL", yasakliKelimeler: ["SULU","MİDE","BOZMAK","TUVALET","BAĞIRSAK"]),
  TabuKart(anaKelime: "LEBİDERYA", yasakliKelimeler: ["DENİZ KENARI","SAHİL","EV","YAZLIK","MANZARA"]),
  TabuKart(anaKelime: "HELLİM PEYNİRİ", yasakliKelimeler: ["KIBRIS","SALATA","KAŞAR","KIZARTMAK","KAHVALTI"]),
  TabuKart(anaKelime: "REKOLTE", yasakliKelimeler: ["TARIM","ÜRÜN","YIL","ALMAK","TARLA"]),
  TabuKart(anaKelime: "DURAK", yasakliKelimeler: ["OTOBÜS","TREN","DOLMUŞ","İNMEK","BİNMEK"]),
  TabuKart(anaKelime: "LOKAVT", yasakliKelimeler: ["GREV","İŞÇİ","ÇIKARMAK","PATRON","TOPLU"]),
  TabuKart(anaKelime: "NİŞASTA", yasakliKelimeler: ["ŞEKER","KARBONHİDRAT","YİYECEK","PATATES","MISIR"]),
  TabuKart(anaKelime: "ŞEBNEM FERAH", yasakliKelimeler: ["ŞARKICI","KADIN","ROCK","VOLVOX","VOKAL"]),
  TabuKart(anaKelime: "CAN SİMİDİ", yasakliKelimeler: ["DENİZ","YUVARLAK","TAKMAK","BOĞULMAK","VAPUR"]),
  TabuKart(anaKelime: "KAMP", yasakliKelimeler: ["ÇADIR","ORMAN","ATEŞ","UYKU TULUMU","İZCİ"]),
  TabuKart(anaKelime: "SONRADAN GÖRME", yasakliKelimeler: ["ZENGİN","FAKİR","GÖSTERİŞ","ÖVÜNMEK","ABARTMAK"]),
  TabuKart(anaKelime: "KIYASIYA", yasakliKelimeler: ["MÜCADELE","ZORLU","REKABET","ÇEKİŞMELİ","KIRAN KIRANA"]),
  TabuKart(anaKelime: "KANTİN", yasakliKelimeler: ["OKUL","TOST","KAFETERYA","ÖĞRENCİ","YEMEK"]),
  TabuKart(anaKelime: "TAKMA DİŞ", yasakliKelimeler: ["AĞIZ","YEMEK","YAŞLI","DÖKÜLMEK","DAMAK"]),
  TabuKart(anaKelime: "BEKÇİ", yasakliKelimeler: ["DÜDÜK","HIRSIZ","GÜVENLİK","KULÜBE","KORUMAK"]),
  TabuKart(anaKelime: "FOS ÇIKMAK", yasakliKelimeler: ["GÜVENMEK","GERÇEKLEŞMEK","UMMAK","BOŞ","BEKLEMEK"]),
  TabuKart(anaKelime: "DANIEL CRAIG", yasakliKelimeler: ["JAMES BOND","AKTÖR","007","SARIŞIN","AJAN"]),
  TabuKart(anaKelime: "MALTA", yasakliKelimeler: ["ADA","ŞOVALYE","ÜLKE","AKDENİZ","ERİK"]),
  TabuKart(anaKelime: "FİLE", yasakliKelimeler: ["PAZAR","TORBA","İP","BASKETBOL","TAŞIMAK"]),
  TabuKart(anaKelime: "ZINEDINE ZIDANE", yasakliKelimeler: ["FUTBOL","JUBİLE","CEZAYİR","FRANSA","REAL MADRİD"]),
  TabuKart(anaKelime: "MENEMEN", yasakliKelimeler: ["YEMEK","YUMURTA","DOMATES","TAVA","BİBER"]),
  TabuKart(anaKelime: "TUNİK", yasakliKelimeler: ["GİYSİ","PANTOLON","ETEK","UZUN","ELBİSE"]),
  TabuKart(anaKelime: "KÖSTEK OLMAK", yasakliKelimeler: ["ENGEL","MANİ","DESTEK","YARDIM","ÖNLEMEK"]),
  TabuKart(anaKelime: "ÇAPAK", yasakliKelimeler: ["GÖZ","SABAH","KURUMAK","UYKU","KENAR"]),
  TabuKart(anaKelime: "BOZKIR", yasakliKelimeler: ["BİTKİ","TOPRAK","KIRAÇ","ÇAYIR","ORMAN"]),
  TabuKart(anaKelime: "VATANDAŞ", yasakliKelimeler: ["ÜLKE","MİLLET","YURTTAŞ","YAŞAMAK","PASAPORT"]),
  TabuKart(anaKelime: "BADEM EZMESİ", yasakliKelimeler: ["TATLI","ŞEKERLEME","YİYECEK","LOKUM","FISTIK"]),
  TabuKart(anaKelime: "KARNABAHAR", yasakliKelimeler: ["SEBZE","MEYVE","YEMEK","BEYAZ","BROKOLİ"]),
  TabuKart(anaKelime: "ÇEKİCİ", yasakliKelimeler: ["KADIN","GÜZEL","SEKSİ","ALIMLI","İTİCİ"]),
  TabuKart(anaKelime: "CANAN", yasakliKelimeler: ["SEVGİLİ","AŞIK OLMAK","GÖNÜL VERMEK","KADIN","YAR"]),
  TabuKart(anaKelime: "TUĞRA", yasakliKelimeler: ["OSMANLI","İMZA","PADİŞAH","SEMBOL","İSİM"]),
  TabuKart(anaKelime: "BLENDER", yasakliKelimeler: ["KARIŞTIRMAK","PARÇALAMAK","MUTFAK","ALET","YEMEK"]),
  TabuKart(anaKelime: "KROMOZOM", yasakliKelimeler: ["X","Y","GENETİK","DNA","HÜCRE"]),
  TabuKart(anaKelime: "SİYAH KUŞAK", yasakliKelimeler: ["UZAK DOĞU","JUDO","KARATE","SPOR","AİKİDO"]),
  TabuKart(anaKelime: "BÜZGÜ", yasakliKelimeler: ["DİKMEK","KUMAŞ","İPLİK","KIVRIM","BOLLUK"]),
  TabuKart(anaKelime: "NÜFUS SAYIMI", yasakliKelimeler: ["ÜLKE","YAŞAMAK","İNSAN","MEMUR","EV"]),
  TabuKart(anaKelime: "KETEN", yasakliKelimeler: ["KUMAŞ","PANTOLON","YAZLIK","CEKET","BURUŞMAK"]),
  TabuKart(anaKelime: "HACI BEKTAŞ-I VELİ", yasakliKelimeler: ["ALEVİ","TASAVVUF","ŞENLİK","MEVLANA","FIKRA"]),
  TabuKart(anaKelime: "VAZELİN", yasakliKelimeler: ["YUMUŞAK","SÜRMEK","EL","AYAK","KREM"]),
  TabuKart(anaKelime: "AMONYAK", yasakliKelimeler: ["SULU","TEMİZLİK","KOKU","ARI SOKMASI","SAÇ BOYASI"]),
  TabuKart(anaKelime: "SOLARYUM", yasakliKelimeler: ["GÜNEŞ","YANMAK","BRONZLAŞMAK","TEN","ESMER"]),
  TabuKart(anaKelime: "MAKSAT", yasakliKelimeler: ["AMAÇ","AŞMAK","İSTEMEK","NEDEN","SEBEP"]),
  TabuKart(anaKelime: "GENSORU", yasakliKelimeler: ["TBMM","ÖNERGE","BAKAN","MİLLETVEKİLİ","SORUŞTURMA"]),
  TabuKart(anaKelime: "MESİRE", yasakliKelimeler: ["YER","PİKNİK","GEZMEK","AĞAÇLIK","DOĞAL"]),
  TabuKart(anaKelime: "BOA YILANI", yasakliKelimeler: ["HAYVAN","KOBRA","SÜRÜNGEN","UZUN","BÜYÜK"]),
  TabuKart(anaKelime: "KORNEA", yasakliKelimeler: ["GÖZ","İRİS","GÖRMEK","PARÇA","YIRTMAK"]),
  TabuKart(anaKelime: "MİZANSEN", yasakliKelimeler: ["YARATMAK","TAKLİT","SİNEMA","DÜZENLEMEK","SAHNE"]),
  TabuKart(anaKelime: "RANZA", yasakliKelimeler: ["YATAK","İKİ","KAT","KOĞUŞ","UYUMAK"]),
  TabuKart(anaKelime: "ABİDİN DİNO", yasakliKelimeler: ["RESSAM","NAZIM HİKMET","FRANSA","MUTLULUK","SERGİ"]),
  TabuKart(anaKelime: "SİNEMASKOP", yasakliKelimeler: ["GENİŞ","SİYAH","BANT","ÇERÇEVE","FİLM"]),
  TabuKart(anaKelime: "TESLİMAT", yasakliKelimeler: ["POSTA","KARGO","GÖNDERMEK","MEKTUP","ALMAK"]),
  TabuKart(anaKelime: "BİLMECE", yasakliKelimeler: ["BULMACA","TEKERLEME","GİZLİ","SORMAK","OYUN"]),
  TabuKart(anaKelime: "BANDANA", yasakliKelimeler: ["SAÇ","TAKMAK","EŞARP","BAĞLAMAK","GÜNEŞ"]),
  TabuKart(anaKelime: "PÜSKÜRMEK", yasakliKelimeler: ["YANARDAĞ","LAV","SU","ÇIKARMAK","FIŞKIRMAK"]),
  TabuKart(anaKelime: "ARSIZ", yasakliKelimeler: ["ŞIMARIK","TERBİYESİZ","DAYAK","UTANMAZ","YÜZSÜZ"]),
  TabuKart(anaKelime: "KORTEJ", yasakliKelimeler: ["TÖREN","KONVOY","ASKER","YÜRÜMEK","SIRA"]),
  TabuKart(anaKelime: "ANKA KUŞU", yasakliKelimeler: ["HAYALİ","MASAL","EFSANE","KAF DAĞI","KÜL"]),
  TabuKart(anaKelime: "HAMLET", yasakliKelimeler: ["KAHRAMAN","'OLMAK YADA OLMAMAK'","SHAKESPEARE","TİYATRO","SİNEMA"]),
  TabuKart(anaKelime: "STEPNE", yasakliKelimeler: ["LASTİK","YEDEK","TEKERLEK","ARABA","PATLATMAK"]),
  TabuKart(anaKelime: "PANZEHİR", yasakliKelimeler: ["ŞIRINGA","İYİLEŞTİRMEK","MADDE","SOKMAK","YILAN"]),
  TabuKart(anaKelime: "DEFNE", yasakliKelimeler: ["YAPRAK","AĞAÇ","BALIK","KOKMAK","MİTOLOJİ"]),
  TabuKart(anaKelime: "CANINA KASDETMEK", yasakliKelimeler: ["TEŞEBBÜS","ÖLDÜRMEK","YARALAMAK","CİNAYET","HAZIRLANMAK"]),
  TabuKart(anaKelime: "SU TOPLAMAK", yasakliKelimeler: ["YARA","AYAK","YÜRÜMEK","EL","ŞİŞMEK"]),
  TabuKart(anaKelime: "İSYANKAR", yasakliKelimeler: ["ASİ","GENÇ","DELİKANLI","BAŞKALDIRMAK","KAVGA"]),
  TabuKart(anaKelime: "PUF", yasakliKelimeler: ["KOLTUK","OTURMAK","MİNDER","YUMUŞAK","ARMUT"]),
  TabuKart(anaKelime: "SÜTLİMAN", yasakliKelimeler: ["SAKİN","SESSİZ","HUZURLU","DURGUN","OLAY"]),
  TabuKart(anaKelime: "MİSTİK", yasakliKelimeler: ["FAL","DOĞAÜSTÜ","GÜÇ","GİZEM","ESRARENGİZ"]),
  TabuKart(anaKelime: "GEBE", yasakliKelimeler: ["HAMİLE","KADIN","BEBEK","DOKUZ AY","KARIN"]),
  TabuKart(anaKelime: "MAESTRO", yasakliKelimeler: ["ORKESTRA","YÖNETMEN","ŞEF","BESTECİ","KLASİK MÜZİK"]),
  TabuKart(anaKelime: "KOKOŞ", yasakliKelimeler: ["SÜSLÜ","GİYİNMEK","HAVALI","AŞIRI","TAKIŞTIRMAK"]),
  TabuKart(anaKelime: "SÖĞÜŞ", yasakliKelimeler: ["DOMATES","SALATALIK","KESMEK","SOĞUK","ET"]),
  TabuKart(anaKelime: "TON BALIĞI", yasakliKelimeler: ["SANDVİÇ","KONSERVE","ORKİNOS","SALATA","YEMEK"]),
  TabuKart(anaKelime: "KÜFE", yasakliKelimeler: ["SEPET","TAŞIMAK","HAMAL","YÜK","SIRT"]),
  TabuKart(anaKelime: "KAYDIRAK", yasakliKelimeler: ["OYUN","PARK","ÇOCUK","SALINCAK","TAHTEREVALLİ"]),
  TabuKart(anaKelime: "KIŞ UYKUSU", yasakliKelimeler: ["AYI","YATMAK","SOĞUK","SÜRÜNGEN","HAYVAN"]),
  TabuKart(anaKelime: "MOTİVASYON", yasakliKelimeler: ["TEŞVİK","KIRMAK","İSTEK","MORAL","HEVES"]),
  TabuKart(anaKelime: "GÖZ KULAK OLMAK", yasakliKelimeler: ["İLGİLENMEK","ÇOCUK","BAKMAK","KORUMAK","BIRAKMAK"]),
  TabuKart(anaKelime: "SULUBOYA", yasakliKelimeler: ["YAĞLIBOYA","RESİM","FIRÇA","PALET","RENK"]),
  TabuKart(anaKelime: "BARUT", yasakliKelimeler: ["FIÇI","ATEŞ","PATLAMAK","TOP","SİLAH"]),
  TabuKart(anaKelime: "AĞIRBAŞLI", yasakliKelimeler: ["CİDDİ","OLGUN","HAREKET","SESSİZ","DAVRANIŞ"]),
  TabuKart(anaKelime: "ANTİKOR", yasakliKelimeler: ["HASTALIK","ZARAR","MADDE","VÜCUT","ÜRETMEK"]),
  TabuKart(anaKelime: "OBJEKTİF", yasakliKelimeler: ["FOTOĞRAF","MERCEK","KAMERA","CAM","TARAFSIZ"]),
  TabuKart(anaKelime: "MAŞALLAH", yasakliKelimeler: ["ALTIN","SÜNNET","NAZAR","GÜZEL","BEĞENMEK"]),
  TabuKart(anaKelime: "KİLOGRAM", yasakliKelimeler: ["ÖLÇÜ","TARTMAK","LİTRE","AĞIRLIK","BİRİM"]),
  TabuKart(anaKelime: "PARKE", yasakliKelimeler: ["YER","DÖŞEMEK","LAMİNANT","YÜRÜMEK","AHŞAP"]),
  TabuKart(anaKelime: "ŞÖLEN", yasakliKelimeler: ["KUTLAMA","YEMEK","İÇMEK","ZİYAFET","EĞLENCE"]),
  TabuKart(anaKelime: "MUTANT", yasakliKelimeler: ["X-MEN","NİNJA KAPLUMBAĞALAR","İNSAN","DEĞİŞMEK","YARATIK"]),
  TabuKart(anaKelime: "ÇATALHÖYÜK", yasakliKelimeler: ["ARKEOLOJİ","ANTİK","ANADOLU","ESKİ","KAZI"]),
  TabuKart(anaKelime: "ANANAS", yasakliKelimeler: ["MEYVE","TROPİKAL","SEBZE","YEMEK","KONSERVE"]),
  TabuKart(anaKelime: "AŞIK VEYSEL", yasakliKelimeler: ["MÜZİK","TÜRKÜ","TÜRK","OZAN","HALK"]),
  TabuKart(anaKelime: "MANGA", yasakliKelimeler: ["ÇİZGİ ROMAN","ANİMASYON","JAPON","ASKER","TABUR"]),
  TabuKart(anaKelime: "FOKURDAMAK", yasakliKelimeler: ["KAYNAMAK","SU","BALONCUK","SES ÇIKARMAK","BUHARLAŞMAK"]),
  TabuKart(anaKelime: "KOMİ", yasakliKelimeler: ["GARSON","MUTFAK","LOKANTA","RESTORAN","YARDIMCI"]),
  TabuKart(anaKelime: "MARJ", yasakliKelimeler: ["KAR","PAY","AYIRMAK","FİYAT","BOŞLUK"]),
  TabuKart(anaKelime: "METEOROLOJİ", yasakliKelimeler: ["HAVA DURUMU","TAHMİN","YAĞMUR","KAR","SICAKLIK"]),
  TabuKart(anaKelime: "SFENKS", yasakliKelimeler: ["MISIR","PİRAMİT","İNSAN","ASLAN","HEYKEL"]),
  TabuKart(anaKelime: "SU AYGIRI", yasakliKelimeler: ["HİPOPOTAM","MEMELİ","HAYVAN","İRİ","AFRİKA"]),
  TabuKart(anaKelime: "BABİL KULESİ", yasakliKelimeler: ["EFSANE","İNŞA ETMEK","TANRI","ULAŞMAK","ESKİ"]),
  TabuKart(anaKelime: "AHENK", yasakliKelimeler: ["UYUM","ŞİİR","SES","DANS","UZLAŞMA"]),
  TabuKart(anaKelime: "POKER", yasakliKelimeler: ["KUMAR","İSKAMBİL KAĞIDI","OYUN","FLOŞ","DÖPER"]),
  TabuKart(anaKelime: "ETÜT", yasakliKelimeler: ["DERS ÇALIŞMAK","ÖĞRETMEN","ÖDEV","OKUL","KALMAK"]),
  TabuKart(anaKelime: "ŞEHZADE", yasakliKelimeler: ["PADİŞAH","ÇOCUK","SULTAN","PRENS","ERKEK"]),
  TabuKart(anaKelime: "KAFADAN ATMAK", yasakliKelimeler: ["UYDURMAK","SALLAMAK","BİLMEK","YALLAH","TEST"]),
  TabuKart(anaKelime: "EFENDİ", yasakliKelimeler: ["BEY","SESLENMEK","KİBAR","AĞIRBAŞLI","NAZİK"]),
  TabuKart(anaKelime: "AYASOFYA MÜZESİ", yasakliKelimeler: ["KİLİSE","TURİST","SULTANAHMET","TOPKAPI SARAYI","CAMİİ"]),
  TabuKart(anaKelime: "PARSEL", yasakliKelimeler: ["ARSA","SATMAK","BÖLÜM","TAPU","PARÇA"]),
  TabuKart(anaKelime: "GÜZELLİK YARIŞMASI", yasakliKelimeler: ["KRALİÇE","MAYO","KAİNAT","JÜRİ","KIZ"]),
  TabuKart(anaKelime: "POHPOHLAMAK", yasakliKelimeler: ["ÖVMEK","YALAKALIK","YAĞ ÇEKMEK","GAZA GETİRMEK","GÜZEL SÖZ"]),
  TabuKart(anaKelime: "EŞEKARISI", yasakliKelimeler: ["BÜYÜK","SOKMAK","BAL","KOVAN","İĞNE"]),
  TabuKart(anaKelime: "ERTUĞRUL ÖZKÖK", yasakliKelimeler: ["GAZETECİ","HÜRRİYET","YAZAR","YÖNETİCİ","YAYIN"]),
  TabuKart(anaKelime: "BEL BAĞLAMAK", yasakliKelimeler: ["GÜVENMEK","YARDIM","MEDET UMMAK","İNANMAK","ARKADAŞ"]),
  TabuKart(anaKelime: "KOTA", yasakliKelimeler: ["DOLDURMAK","KONTENJAN","SINIRLAMA","KISITLAMA","SAYI"]),
  TabuKart(anaKelime: "BUZ DEVRİ", yasakliKelimeler: ["ESKİ ÇAĞ","SOĞUK","ERİMEK","KAR","ÇİZGİ FİLM"]),
  TabuKart(anaKelime: "İMSAK", yasakliKelimeler: ["İFTAR","ORUÇ","SAHUR","RAMAZAN","EZAN"]),
  TabuKart(anaKelime: "BAYKUŞ", yasakliKelimeler: ["HAYVAN","KUŞ","GECE","UÇMAK","UĞURSUZ"]),
  TabuKart(anaKelime: "TARAFTAR", yasakliKelimeler: ["FUTBOL","TAKIM","TUTMAK","FANATİK","TEZAHÜRAT"]),
  TabuKart(anaKelime: "SU BASKINI", yasakliKelimeler: ["SEL","YAĞMUR","MUSLUK","AÇIK","TAŞMAK"]),
  TabuKart(anaKelime: "ŞEKERPARE", yasakliKelimeler: ["TATLI","ŞERBET","HAMUR","YUVARLAK","YEMEK"]),
  TabuKart(anaKelime: "KÖRDÜĞÜM", yasakliKelimeler: ["İP","AÇILMAK","KARIŞIK","ÇÖZMEK","BAĞLAMAK"]),
  TabuKart(anaKelime: "KADEH", yasakliKelimeler: ["İÇECEK","BARDAK","ŞARAP","CAM","RAKI"]),
  TabuKart(anaKelime: "KALIBINI BASMAK", yasakliKelimeler: ["SAVUNMAK","İNANMAK","İDDİA","GÜVENMEK","DOĞRU"]),
  TabuKart(anaKelime: "NEMRUT DAĞI", yasakliKelimeler: ["ADIYAMAN","ARKEOLOJİ","HEYKEL","GÜNBATIMI","TANRI"]),
  TabuKart(anaKelime: "PALA BIYIK", yasakliKelimeler: ["SAKAL","YÜZ","YANAK","UZUN","KIVRIK"]),
  TabuKart(anaKelime: "FELAKET TELLALI", yasakliKelimeler: ["KÖTÜMSER","ANLATMAK","SÖYLEMEK","HABER","OLAY"]),
  TabuKart(anaKelime: "PEKMEZ", yasakliKelimeler: ["TAHİN","ÜZÜM","DUT","TATLI","REÇEL"]),
  TabuKart(anaKelime: "YOUTUBE", yasakliKelimeler: ["VİDEO","PAYLAŞMAK","YÜKLEMEK","İNTERNET","SİTE"]),
  TabuKart(anaKelime: "CADI KAZANI", yasakliKelimeler: ["DÜŞMAN","HİLE","KAYNAMAK","DEDİKODU","DÜZEN"]),
  TabuKart(anaKelime: "ÇAYIR", yasakliKelimeler: ["OTLAMAK","İNEK","YEŞİL","ÇİMEN","PİKNİK"]),
  TabuKart(anaKelime: "KRAVAT", yasakliKelimeler: ["PAPYON","TAKMAK","GÖMLEK","TAKIM ELBİSE","BOYUN"]),
  TabuKart(anaKelime: "TÖKEZLEMEK", yasakliKelimeler: ["SENDELEMEK","DÜŞMEK","AYAK","TAKILMAK","TAŞ"]),
  TabuKart(anaKelime: "LOGO", yasakliKelimeler: ["ŞİRKET","SEMBOL","İSİM","AMBLEM","KURUMSAL"]),
  TabuKart(anaKelime: "SOLAK", yasakliKelimeler: ["SAĞLAK","EL","YAZMAK","TUTMAK","KULLANMAK"]),
  TabuKart(anaKelime: "FLORENCE NİGHTİNGALE", yasakliKelimeler: ["HEMŞİRE","HASTANE","KURMAK","SELİMİYE KIŞLASI","DOKTOR"]),
  TabuKart(anaKelime: "İZDİVAÇ", yasakliKelimeler: ["EVLENMEK","YUVA","GELİN","DAMAT","NİKAH"]),
  TabuKart(anaKelime: "BENEK", yasakliKelimeler: ["ÇİL","NOKTA","YÜZ","LEKE","KÜÇÜK"]),
  TabuKart(anaKelime: "KABZA", yasakliKelimeler: ["SİLAH","TABANCA","TUTMAK","SAP","KILIÇ"]),
  TabuKart(anaKelime: "DOLMABAHÇE SARAYI", yasakliKelimeler: ["OSMANLI","BEŞİKTAŞ","ATATÜRK","PADİŞAH","TOPKAPI"]),
  TabuKart(anaKelime: "İRMİK", yasakliKelimeler: ["HELVA","TATLI","BUĞDAY","UN","DAĞITMAK"]),
  TabuKart(anaKelime: "HAZIRCEVAP", yasakliKelimeler: ["SORU","LAF","ÇABUK","BULMAK","HIZLI"]),
  TabuKart(anaKelime: "UKRAYNA", yasakliKelimeler: ["ÜLKE","RUSYA","KİEV","DOĞALGAZ","KARADENİZ"]),
  TabuKart(anaKelime: "ÇAR", yasakliKelimeler: ["RUSYA","PETRO","PADİŞAH","KRAL","YÖNETMEK"]),
  TabuKart(anaKelime: "POST", yasakliKelimeler: ["HAYVAN","DERİ","YÜZMEK","KÜRK","AYI"]),
  TabuKart(anaKelime: "LİBERO", yasakliKelimeler: ["FUTBOL","TAKIM","MAÇ","DEFANS","ORTA SAHA"]),
  TabuKart(anaKelime: "DEHLİZ", yasakliKelimeler: ["KORİDOR","YER ALTI","GİZLİ","KARANLIK","GEÇİT"]),
  TabuKart(anaKelime: "ÇELİK KASA", yasakliKelimeler: ["PARA","DEĞERLİ","MÜCEVHER","EV","SAKLAMAK"]),
  TabuKart(anaKelime: "MÜJDE AR", yasakliKelimeler: ["SİNEMA","OYUNCU","SEKSİ","AYSEL GÜRSEL","ARABESK"]),
  TabuKart(anaKelime: "FÖN ÇEKMEK", yasakliKelimeler: ["KUAFÖR","SAÇ","DÜZLEŞTİRMEK","MAKİNE","SICAK"]),
  TabuKart(anaKelime: "FAVORİ", yasakliKelimeler: ["BİRİNCİ","YARIŞMA","BEĞENMEK","SEVMEK","SAKAL"]),
  TabuKart(anaKelime: "BABACAN", yasakliKelimeler: ["DAVRANMAK","GÜVENMEK","ADAM","ŞEFKAT","İYİ"]),
  TabuKart(anaKelime: "ASPENDOS", yasakliKelimeler: ["TİYATRO","ANTİK","ANTALYA","AÇIK HAVA","KONSER"]),
  TabuKart(anaKelime: "KÜLAH", yasakliKelimeler: ["ŞAPKA","KAĞIT","DONDURMA","DEĞİŞMEK","ANLATMAK"]),
  TabuKart(anaKelime: "SLALOM", yasakliKelimeler: ["KAYAK","KAR","YARIŞ","BAYRAK","PİST"]),
  TabuKart(anaKelime: "ANTRENMAN", yasakliKelimeler: ["SPOR","KOŞU","EGZERSİZ","FUTBOLCU","İDMAN"]),
  TabuKart(anaKelime: "SAİT FAİK ABASIYANIK", yasakliKelimeler: ["EDEBİYAT","YAZAR","HİKAYE","TÜRK","BURGAZADA"]),
  TabuKart(anaKelime: "ÇİVİ YAZISI", yasakliKelimeler: ["İLKÇAĞ","ESKİ","ASUR","SÜMER","TAŞ"]),
  TabuKart(anaKelime: "AKROBAT", yasakliKelimeler: ["GÖSTERİ","YETENEK","SİRK","CAMBAZ","ESNEK"]),
  TabuKart(anaKelime: "KOLONYA", yasakliKelimeler: ["FERAHLIK","SÜRMEK","LİMON","DÖKMEK","MİSAFİR"]),
  TabuKart(anaKelime: "CANNES", yasakliKelimeler: ["FİLM","FESTİVAL","FRANSA","SAHİL","SİNEMA"]),
  TabuKart(anaKelime: "ESPRİ YAPMAK", yasakliKelimeler: ["KOMİK","ŞAKA","ANLATMAK","GÜLMEK","KAHKAHA"]),
  TabuKart(anaKelime: "MAKBUZ", yasakliKelimeler: ["AİDAT","BAĞIŞ","ÖDEME","KAĞIT","FATURA"]),
  TabuKart(anaKelime: "MÜHİMMAT", yasakliKelimeler: ["DEPO","SAVAŞ","CEPHANE","ORDU","SİLAH"]),
  TabuKart(anaKelime: "GONG", yasakliKelimeler: ["SES","ZİL","TOKMAK","ÇINLAMAK","VURMAK"]),
  TabuKart(anaKelime: "SOĞUK ALGINLIĞI", yasakliKelimeler: ["NEZLE","ÜŞÜTMEK","HASTA","BURUN","BOĞAZ"]),
  TabuKart(anaKelime: "ÇAĞLAYAN", yasakliKelimeler: ["ŞELALE","SU","AKMAK","NEHİR","YÜKSEK"]),
  TabuKart(anaKelime: "İMAMBAYILDI", yasakliKelimeler: ["YEMEK","PATLICAN","ZEYTİNYAĞLI","KARNIYARIK","DOMATES"]),
  TabuKart(anaKelime: "MACERA", yasakliKelimeler: ["OLAY","HEYECAN","ADRENALİN","YAŞAMAK","SAKİN"]),
  TabuKart(anaKelime: "AHMET ÇAKAR", yasakliKelimeler: ["HAKEM","FUTBOL","ERMAN TOROĞLU","YARIŞMA","MAÇ"]),
  TabuKart(anaKelime: "KALÇA", yasakliKelimeler: ["KADIN","SALLAMAK","VÜCUT","BACAK","JENNİFER LOPEZ"]),
  TabuKart(anaKelime: "HAKARET ETMEK", yasakliKelimeler: ["KÜFÜR","SÖZ","KÖTÜ","SÖYLEMEK","ÇİRKİN"]),
  TabuKart(anaKelime: "KONDİSYON BİSİKLETİ", yasakliKelimeler: ["SPOR","EV","ÇEVİRMEK","KOŞU BANDI","ZAYIFLAMAK"]),
  TabuKart(anaKelime: "PAVURYA", yasakliKelimeler: ["YENGEÇ","İRİ","BÜYÜK","DENİZ","YEMEK"]),
  TabuKart(anaKelime: "PATENT", yasakliKelimeler: ["ALMAK","TESCİL","BULUŞ","TELİF HAKKI","KANITLAMAK"]),
  TabuKart(anaKelime: "ŞİŞİRMEK", yasakliKelimeler: ["BALON","LASTİK","ÜFLEMEK","POMPA","HAVA"]),
  TabuKart(anaKelime: "HAFRİYAT", yasakliKelimeler: ["İNŞAAT","TOPRAK","BİNA","KAZMAK","KAMYON"]),
  TabuKart(anaKelime: "ASTRONOMİK", yasakliKelimeler: ["RAKAM","YÜKSEK","PAHALI","AŞIRI","GÖKYÜZÜ"]),
  TabuKart(anaKelime: "KAYKAY", yasakliKelimeler: ["BİNMEK","ÇOCUK","TEKERLEK","TAHTA","PATEN"]),
  TabuKart(anaKelime: "MAVİ YOLCULUK", yasakliKelimeler: ["EGE","GEZİ","YAT","KİRALAMAK","AKDENİZ"]),
  TabuKart(anaKelime: "BOŞ BULUNMAK", yasakliKelimeler: ["DİKKATSİZ","DALGIN","DAVRANMAK","SÖYLEMEK","POT KIRMAK"]),
  TabuKart(anaKelime: "ORHAN GENCEBAY", yasakliKelimeler: ["MÜZİSYEN","ARABESK","FERDİ TAYFUR","MÜSLÜM GÜRSES","BATSIN BU DÜNYA"]),
  TabuKart(anaKelime: "DIŞLANMAK", yasakliKelimeler: ["ARKADAŞ","KONUŞMAK","ATMAK","ALMAK","ORTAM"]),
  TabuKart(anaKelime: "NEŞTER", yasakliKelimeler: ["AMELİYAT","BIÇAK","KESMEK","CERRAH","DOKTOR"]),
  TabuKart(anaKelime: "ŞEBEKE", yasakliKelimeler: ["AĞ","DONANIM","ÖRGÜT","ELEKTRİK","TESİSAT"]),
  TabuKart(anaKelime: "YAREN", yasakliKelimeler: ["DOST","ARKADAŞ","SEVGİLİ","YAKIN","EŞ"]),
  TabuKart(anaKelime: "SERE SERPE", yasakliKelimeler: ["GÜNEŞLENMEK","YATMAK","RAHAT","AÇIK SAÇIK","SERBEST"]),
  TabuKart(anaKelime: "TOKYO", yasakliKelimeler: ["ŞEHİR","JAPONYA","ADA","ASYA","BAŞKENT"]),
  TabuKart(anaKelime: "İÇİNE DOĞMAK", yasakliKelimeler: ["HİSSETMEK","ÖNCE","BİLMEK","MALUM OLMAK","SEZMEK"]),
  TabuKart(anaKelime: "BANKO", yasakliKelimeler: ["KESİN","AT YARIŞI","KAZANMAK","BAHİS","GARANTİ"]),
  TabuKart(anaKelime: "PİSBOĞAZ", yasakliKelimeler: ["OBUR","YEMEK","AÇGÖZLÜ","TOK","DOYMAK"]),
  TabuKart(anaKelime: "ÇOBANYILDIZI", yasakliKelimeler: ["GÖKYÜZÜ","GECE","YÖN","PARLAK","KUTUP"]),
  TabuKart(anaKelime: "ALASKA", yasakliKelimeler: ["FRİGO","AMERİKA","SOĞUK","EYALET","RUSYA"]),
  TabuKart(anaKelime: "BEYZBOL", yasakliKelimeler: ["SPOR","AMERİKA","TOP","VURMAK","SOPA"]),
  TabuKart(anaKelime: "GÖRGÜ KURALLARI", yasakliKelimeler: ["ADAP","SAYGI","TERBİYE","TOPLUM","UYMAK"]),
  TabuKart(anaKelime: "ÇİÇEK PASAJI", yasakliKelimeler: ["İSTANBUL","BEYOĞLU","NEVİZADE","YEMEK","İÇMEK"]),
  TabuKart(anaKelime: "KAĞIT HELVA", yasakliKelimeler: ["YİYECEK","TATLI","YUVARLAK","DONDURMA","KÜLAH"]),
  TabuKart(anaKelime: "DAMLA", yasakliKelimeler: ["SU","MUSLUK","GÖZ","YAĞMUR","KÜÇÜK"]),
  TabuKart(anaKelime: "DENEY", yasakliKelimeler: ["KİMYA","LABORATUAR","FARE","BİLİM","TÜP"]),
  TabuKart(anaKelime: "TUŞ KİLİDİ", yasakliKelimeler: ["TELEFON","AÇIK","KAPALI","BASMAK","ARAMAK"]),
  TabuKart(anaKelime: "MİLADİ TAKVİM", yasakliKelimeler: ["GÜN","AY","ZAMAN","AJANDA","HİCRİ"]),
  TabuKart(anaKelime: "KÖŞE BUCAK", yasakliKelimeler: ["KAÇMAK","TEMİZLEMEK","HER YER","SAKLANMAK","DOLAŞMAK"]),
  TabuKart(anaKelime: "RENGİ ATMAK", yasakliKelimeler: ["KORKMAK","YIKAMAK","SOLMAK","YÜZ","SARARMAK"]),
  TabuKart(anaKelime: "ALP ARSLAN", yasakliKelimeler: ["SELÇUKLU","HÜKÜMDAR","TÜRK","ANADOLU","MALAZGİRT SAVAŞI"]),
  TabuKart(anaKelime: "KOLERA", yasakliKelimeler: ["HASTALIK","SALGIN","TİFO","İSHAL","BULAŞICI"]),
  TabuKart(anaKelime: "EBEVEYN", yasakliKelimeler: ["ANNE","BABA","ÇOCUK","AİLE","İKİLİ"]),
  TabuKart(anaKelime: "FRAPAN", yasakliKelimeler: ["ELBİSE","GİYSİ","DİKKAT ÇEKİCİ","RÜKÜŞ","HAVALI"]),
  TabuKart(anaKelime: "KONTAK", yasakliKelimeler: ["KAFA","LENS","ANAHTAR","ARABA","TEMAS"]),
  TabuKart(anaKelime: "MURATHAN MUNGAN", yasakliKelimeler: ["EDEBİYAT","ŞAİR","ROMAN","YAZAR","KIRK ODA"]),
  TabuKart(anaKelime: "BACANAK", yasakliKelimeler: ["EŞ","KARDEŞ","BALDIZ","KOCA","KIZ"]),
  TabuKart(anaKelime: "PSİKOLOJİ", yasakliKelimeler: ["SOSYOLOJİ","PSİKİYATRİ","RUHBİLİM","DEPRESYON","FREUD"]),
  TabuKart(anaKelime: "RİZİKO", yasakliKelimeler: ["RİSK","ZARAR","TEHLİKE","YARIŞMA","TELEVİZYON"]),
  TabuKart(anaKelime: "DALGAKIRAN", yasakliKelimeler: ["DENİZ","BETON","KAYA","TEKNE","SET"]),
  TabuKart(anaKelime: "REHİN VERMEK", yasakliKelimeler: ["KUYUMCU","BORÇ","PARA","MÜCEVHER","ALTIN"]),
  TabuKart(anaKelime: "ZORUNA GİTMEK", yasakliKelimeler: ["BOZULMAK","ÜZÜLMEK","GÜCÜNE GİTMEK","DOKUNMAK","ONUR"]),
  TabuKart(anaKelime: "ROKET", yasakliKelimeler: ["FÜZE","ATMAK","SAVAŞ","SİLAH","MENZİL"]),
  TabuKart(anaKelime: "KARİDES", yasakliKelimeler: ["DENİZ","KABUKLU","JUMBO","ISTAKOZ","GÜVEÇ"]),
  TabuKart(anaKelime: "DEJENERE", yasakliKelimeler: ["BOZULMAK","GENÇLİK","YOZLAŞMAK","NESİL","TOPLUM"]),
  TabuKart(anaKelime: "ÇERKEZTAVUĞU", yasakliKelimeler: ["YEMEK","CEVİZ","MEZE","DİDİKLEMEK","ET"]),
  TabuKart(anaKelime: "İÇERLEMEK", yasakliKelimeler: ["ALINMAK","GÜCENMEK","ÜZÜLMEK","DARILMAK","KIRILMAK"]),
  TabuKart(anaKelime: "HEYBE", yasakliKelimeler: ["ÇANTA","TORBA","EŞEK","TAŞIMAK","OMUZ"]),
  TabuKart(anaKelime: "PANSUMAN", yasakliKelimeler: ["YARA","TEMİZLEMEK","BAKMAK","HEMŞİRE","PAMUK"]),
  TabuKart(anaKelime: "ZAMANE", yasakliKelimeler: ["ÇOCUK","BUGÜN","GENÇ","ŞİMDİ","YAKINMAK"]),
  TabuKart(anaKelime: "ASMA YAPRAĞI", yasakliKelimeler: ["ÜZÜM","DOLMA","ŞARAP","SARMA","ZEYTİNYAĞI"]),
  TabuKart(anaKelime: "SEMER", yasakliKelimeler: ["EYER","EŞEK","AT","SIRT","OTURMAK"]),
  TabuKart(anaKelime: "MUŞMULA", yasakliKelimeler: ["BİTKİ","AĞAÇ","MEYVE","BURUŞUK","SURAT"]),
  TabuKart(anaKelime: "YAZLIK", yasakliKelimeler: ["EV","OTURMAK","GİTMEK","DENİZ","TATİL"]),
  TabuKart(anaKelime: "VOKAL", yasakliKelimeler: ["SES","ŞARKI","SÖYLEMEK","MÜZİK","YAPMAK"]),
  TabuKart(anaKelime: "JAMBON", yasakliKelimeler: ["KAHVALTI","SALAM","ET","SANDVİÇ","DANA"]),
  TabuKart(anaKelime: "ULTRASON", yasakliKelimeler: ["BAKMAK","BEBEK","HAMİLE","ÇEKTİRMEK","RÖNTGEN"]),
  TabuKart(anaKelime: "ALYUVAR", yasakliKelimeler: ["KAN","DAMAR","KIRMIZI","HÜCRE","AKYUVAR"]),
  TabuKart(anaKelime: "TEZKERE", yasakliKelimeler: ["ASKERLİK","BİTİRMEK","BELGE","KAĞIT","ORDU"]),
  TabuKart(anaKelime: "DÜZ TABAN", yasakliKelimeler: ["ASKERLİK","AYAK","YÜRÜMEK","ORTOPEDİ","TOPUK"]),
  TabuKart(anaKelime: "KAYMAKAM", yasakliKelimeler: ["VALİ","İLÇE","YÖNETMEK","MEMUR","BELEDİYE"]),
  TabuKart(anaKelime: "KALAY", yasakliKelimeler: ["BAKIR","TENCERE","KAP KACAK","AZARLAMAK","PARLATMAK"]),
  TabuKart(anaKelime: "İLMEK", yasakliKelimeler: ["DÜĞÜM","HALI","ÖRMEK","ŞİŞ","TIĞ"]),
  TabuKart(anaKelime: "KANALİZASYON", yasakliKelimeler: ["LAĞIM","TUVALET","PİS","SU","YER ALTI"]),
  TabuKart(anaKelime: "MAHSUL", yasakliKelimeler: ["ÜRÜN","TARLA","TOPLAMAK","VERİM","ÇİFTÇİ"]),
  TabuKart(anaKelime: "BURNUNDAN GETİRMEK", yasakliKelimeler: ["RAHATSIZ ETMEK","FİTİL FİTİL","PİŞMAN ETMEK","BOZMAK","ZEHİR ETMEK"]),
  TabuKart(anaKelime: "CEZVE", yasakliKelimeler: ["KAHVE","FAL","PİŞİRMEK","SAP","TELVE"]),
  TabuKart(anaKelime: "BAHANE", yasakliKelimeler: ["ARAMAK","UYDURMAK","YALAN","SEBEP","SÖYLEMEK"]),
  TabuKart(anaKelime: "KONFETİ", yasakliKelimeler: ["KAĞIT","MAÇ","RENKLİ","ATMAK","DÜĞÜN"]),
  TabuKart(anaKelime: "GANİMET", yasakliKelimeler: ["SAVAŞ","TOPLAMAK","YAĞMA","KORSAN","ÇALMAK"]),
  TabuKart(anaKelime: "JOHN LENNON", yasakliKelimeler: ["MÜZİSYEN","BEATLES","YOKO ONO","ŞARKICI","IMAGİNE"]),
  TabuKart(anaKelime: "FACEBOOK", yasakliKelimeler: ["İNTERNET","ARKADAŞLIK","SİTE","FOTOĞRAF","ÜYE"]),
  TabuKart(anaKelime: "TEKZİP", yasakliKelimeler: ["YALANLAMAK","GERÇEK","GAZETE","YAYINLAMAK","HABER"]),
  TabuKart(anaKelime: "ZİGON", yasakliKelimeler: ["MOBİLYA","İÇ İÇE","SEHPA","MİSAFİR","SALON"]),
  TabuKart(anaKelime: "KOALA", yasakliKelimeler: ["AVUSTRALYA","HAYVAN","AYI","OKALİPTÜS","AĞAÇ"]),
  TabuKart(anaKelime: "SEÇENEK", yasakliKelimeler: ["ŞIK","SINAV","OPSİYON","ALTERNATİF","BAŞKA"]),
  TabuKart(anaKelime: "KUBBE", yasakliKelimeler: ["CAMİİ","YUVARLAK","AYASOFYA","KÜRE","ÇATI"]),
  TabuKart(anaKelime: "HEIDI KLUM", yasakliKelimeler: ["MANKEN","TOP MODEL","SEAL","DEFİLE","ALMAN"]),
  TabuKart(anaKelime: "ÇEMEN", yasakliKelimeler: ["PASTIRMA","ACI","SOS","SÜRMEK","KOKULU"]),
  TabuKart(anaKelime: "DENİZKESTANESİ", yasakliKelimeler: ["BATMAK","DİKEN","KABUK","AYAK","YUVARLAK"]),
  TabuKart(anaKelime: "CASUS", yasakliKelimeler: ["JAMES BOND","GİZLİ","AJAN","MATA HARI","007"]),
  TabuKart(anaKelime: "KUVAY-I MİLLİYE", yasakliKelimeler: ["KURTULUŞ SAVAŞI","MUSTAFA KEMAL ATATÜRK","ORDU","HALK","İSTİKLAL"]),
  TabuKart(anaKelime: "SATIR", yasakliKelimeler: ["BIÇAK","ET","DOĞRAMAK","YAZI","KESMEK"]),
  TabuKart(anaKelime: "LEHİMLEMEK", yasakliKelimeler: ["YAPIŞTIRMAK","TUTTURMAK","METAL","PARÇA","KAYNAK"]),
  TabuKart(anaKelime: "EĞİLİM", yasakliKelimeler: ["İLGİ","YÖNETMEK","MERAK","MEYİL","İSTEMEK"]),
  TabuKart(anaKelime: "DİNOZOR", yasakliKelimeler: ["TÜKENMEK","HAYVAN","JURRASIC PARK","FOSİL","T-REX"]),
  TabuKart(anaKelime: "OKLAVA", yasakliKelimeler: ["HAMUR","AÇMAK","BÖREK","MERDANE","SOPA"]),
  TabuKart(anaKelime: "KÜLBASTI", yasakliKelimeler: ["ET","PİRZOLA","IZGARA","KEMİKSİZ","DANA"]),
  TabuKart(anaKelime: "PLANÖR", yasakliKelimeler: ["UÇMAK","HAVA","GÖKYÜZÜ","MOTOR","KANAT"]),
  TabuKart(anaKelime: "FETHİYE", yasakliKelimeler: ["MUĞLA","ÖLÜDENİZ","TATİL","AKDENİZ","KELEBEKLER VADİSİ"]),
  TabuKart(anaKelime: "LATİN AMERİKA", yasakliKelimeler: ["GÜNEY","KITA","BREZİLYA","ÜLKE","ARJANTİN"]),
  TabuKart(anaKelime: "CANLI YAYIN", yasakliKelimeler: ["TELEVİZYON","NAKLEN","HABER","BAĞLANMAK","MAÇ"]),
  TabuKart(anaKelime: "LCD EKRAN", yasakliKelimeler: ["TELEVİZYON","BİLGİSAYAR","PLAZMA","İNCE","SEYRETMEK"]),
  TabuKart(anaKelime: "GASTRONOMİ", yasakliKelimeler: ["YEMEK","BİLİM","AŞÇI","MUTFAK","GURME"]),
  TabuKart(anaKelime: "GOTİK", yasakliKelimeler: ["ORTAÇAĞ","MİMARİ","GENÇLİK","SİYAH","PUNK"]),
  TabuKart(anaKelime: "ELİŞİ", yasakliKelimeler: ["DANTEL","ÖRGÜ","ÇEYİZ","OKUL","DERS"]),
  TabuKart(anaKelime: "GELİNLİK", yasakliKelimeler: ["EVLİLİK","DUVAK","GİYMEK","BEYAZ","ELBİSE"]),
  TabuKart(anaKelime: "KRATER", yasakliKelimeler: ["AY","GÖKTAŞI","ÇUKUR","YANARDAĞ","VOLKAN"]),
  TabuKart(anaKelime: "NARSİST", yasakliKelimeler: ["HAYRAN","BENCİL","EGOİST","SEVMEK","KENDİ"]),
  TabuKart(anaKelime: "EKÜRİ", yasakliKelimeler: ["AT","İKİLİ","ARKADAŞ","YARIŞ","ORTAK"]),
  TabuKart(anaKelime: "HEBA ETMEK", yasakliKelimeler: ["ZARAR","HARCAMAK","ZİYAN ETMEK","YİTİRMEK","KAYBETMEK"]),
  TabuKart(anaKelime: "TESTERE", yasakliKelimeler: ["FİLM","KORKU","ALET","KESMEK","AĞAÇ"]),
  TabuKart(anaKelime: "KLİP", yasakliKelimeler: ["MÜZİK","VİDEO","TELEVİZYON","İZLEMEK","ÇEKMEK"]),
  TabuKart(anaKelime: "TÖREN", yasakliKelimeler: ["BAYRAK","NİKAH","RESMİ","AÇILIŞ","MERASİM"]),
  TabuKart(anaKelime: "PARMESAN", yasakliKelimeler: ["PEYNİR","SALATA","İTALYAN","MAKARNA","ÜST"]),
  TabuKart(anaKelime: "AFACAN", yasakliKelimeler: ["YARAMAZ","ÇOCUK","ZEKİ","KARIŞTIRMAK","HAYLAZ"]),
  TabuKart(anaKelime: "AMBARGO", yasakliKelimeler: ["KOYMAK","ENGELLEMEK","ÜLKE","TİCARET","UYGULAMAK"]),
  TabuKart(anaKelime: "SANDIK", yasakliKelimeler: ["ÇEYİZ","TAHTA","EŞYA","SEÇİM","OY ATMAK"]),
  TabuKart(anaKelime: "BEŞAMEL", yasakliKelimeler: ["SOS","ET","TAVUK","UN","SÜT"]),
  TabuKart(anaKelime: "İÇİ GEÇMEK", yasakliKelimeler: ["UYUMAK","İSTEMEK","YATMAK","İSTEKSİZ","YAŞLI"]),
  TabuKart(anaKelime: "İSPANYOL PAÇA", yasakliKelimeler: ["PANTOLON","KOT","GENİŞ","UÇ","MODA"]),
  TabuKart(anaKelime: "SÜLALE", yasakliKelimeler: ["AİLE","AKRABA","SOY","TEYZE","AMCA"]),
  TabuKart(anaKelime: "SARPA SARMAK", yasakliKelimeler: ["KARIŞMAK","ÇÖZMEK","İŞ","BOZULMAK","ZORLUK"]),
  TabuKart(anaKelime: "GETTO", yasakliKelimeler: ["MAHALLE","ŞEHİR","AZINLIK","YABANCI","YAŞAMAK"]),
  TabuKart(anaKelime: "IFLAS ETMEK", yasakliKelimeler: ["HACİZ","BANKA","ŞİRKET","BORÇ","BATMAK"]),
  TabuKart(anaKelime: "AÇIK FİKİRLİ", yasakliKelimeler: ["ANLAMAK","MODERN","YENİLİK","DÜŞÜNMEK","BAĞNAZ"]),
  TabuKart(anaKelime: "ÇULLANMAK", yasakliKelimeler: ["ABANMAK","ÜZERİNE GİTMEK","ÜSTÜNE DÜŞMEK","ATLAMAK","ZIPLAMAK"]),
  TabuKart(anaKelime: "JUSTIN TIMBERLAKE", yasakliKelimeler: ["ŞARKICI","AMERİKA","DANS","ERKEK","BRITNEY SPEARS"]),
  TabuKart(anaKelime: "KABAKULAK", yasakliKelimeler: ["ÇOCUK","HASTALIK","KIZAMIK","SUÇİÇEĞİ","ŞİŞMEK"]),
  TabuKart(anaKelime: "GARANTİ BELGESİ", yasakliKelimeler: ["BOZULMAK","TAMİR","YIL","TAAHHÜT","EŞYA"]),
  TabuKart(anaKelime: "EMRİVAKİ YAPMAK", yasakliKelimeler: ["OLDUBİTTİ","ANİ","ACELE","KARGAŞA","ZORLAMAK"]),
  TabuKart(anaKelime: "ROKFOR", yasakliKelimeler: ["PEYNİR","KÜF","SÜT","FRANSIZ","BEYAZ"]),
  TabuKart(anaKelime: "HİLAL", yasakliKelimeler: ["AY","ŞEKİL","DOLUNAY","YILDIZ","BAYRAK"]),
  TabuKart(anaKelime: "ABONE", yasakliKelimeler: ["DERGİ","AY","GAZETE","GELMEK","YONCA EVCİMİK"]),
  TabuKart(anaKelime: "SİVİL TOPLUM", yasakliKelimeler: ["ÖRGÜT","DEVLET","BAĞIMSIZ","DERNEK","VAKIF"]),
  TabuKart(anaKelime: "DONMAK", yasakliKelimeler: ["BUZ","SIFIR","DERECE","SU","KIŞ"]),
  TabuKart(anaKelime: "KAFA DENGİ", yasakliKelimeler: ["ARKADAŞ","UYUMLU","ANLAŞMAK","AYNI","ZEVK"]),
  TabuKart(anaKelime: "SÜVARİ", yasakliKelimeler: ["AT","ASKER","BİNMEK","SAVAŞ","PİYADE"]),
  TabuKart(anaKelime: "SÜKUNET", yasakliKelimeler: ["DURGUN","SESSİZ","HUZURLU","DİNGİN","GÜRÜLTÜLÜ"]),
  TabuKart(anaKelime: "BAŞI BAĞLI", yasakliKelimeler: ["EVLİ","NİŞANLI","SÖZLÜ","BEKAR","SEVGİLİ"]),
  TabuKart(anaKelime: "LÜLETAŞI", yasakliKelimeler: ["PİPO","BEYAZ","OYMAK","YUMUŞAK","ESKİŞEHİR"]),
  TabuKart(anaKelime: "SUSPUS", yasakliKelimeler: ["SİNMEK","KONUŞMAK","SESSİZ","SUÇLU","CEVAP VERMEK"]),
  TabuKart(anaKelime: "JANT", yasakliKelimeler: ["ARABA","PARÇA","TEKERLEK","LASTİK","ÇELİK"]),
  TabuKart(anaKelime: "MESULİYET", yasakliKelimeler: ["SORUMLULUK","GÖREV","İLGİ","YÜKLENMEK","ÜSTLENMEK"]),
  TabuKart(anaKelime: "PASAJ", yasakliKelimeler: ["ÇARŞI","DÜKKAN","BEYOĞLU","ALIŞVERİŞ","KAPALI"]),
  TabuKart(anaKelime: "NOEL BABA", yasakliKelimeler: ["YILBAŞI","HEDİYE","REN GEYİĞİ","BACA","ARALIK"]),
  TabuKart(anaKelime: "AT GÖZLÜĞÜ", yasakliKelimeler: ["SABİT FİKİRLİ","DÜŞÜNMEK","BAKMAK","DAR","TUTUCU"]),
  TabuKart(anaKelime: "BAŞA ÇIKMAK", yasakliKelimeler: ["GÜÇ","YETMEK","BAŞARMAK","ÜSTESİNDEN GELMEK","DERT"]),
  TabuKart(anaKelime: "LOKAL", yasakliKelimeler: ["ANESTEZİ","ULUSLARARASI","DERNEK","GECE KULÜBÜ","YEREL"]),
  TabuKart(anaKelime: "PİYON", yasakliKelimeler: ["SATRANÇ","TAŞ","ŞAH","VEZİR","OYUN"]),
  TabuKart(anaKelime: "ŞAHİN", yasakliKelimeler: ["KARTAL","DOĞAN","KUŞ","YIRTICI","ARABA"]),
  TabuKart(anaKelime: "FOBİ", yasakliKelimeler: ["KORKU","ÖRÜMCEK","YÜKSEKLİK","AŞIRI","PANİK"]),
  TabuKart(anaKelime: "VAKIF", yasakliKelimeler: ["HAYIR İŞİ","BAĞIŞ","KURULUŞ","DERNEK","YARDIM"]),
  TabuKart(anaKelime: "TOLERANS", yasakliKelimeler: ["HOŞGÖRÜ","ANLAYIŞ","GÖSTERMEK","MÜSAMAHA","HATA"]),
  TabuKart(anaKelime: "RASTGELE", yasakliKelimeler: ["HERHANGİ","GELİŞİGÜZEL","SEÇMEK","SESLENMEK","BALIKÇI"]),
  TabuKart(anaKelime: "AFİŞ", yasakliKelimeler: ["ASMAK","DUVAR","KONSER","SİNEMA","FİLM"]),
  TabuKart(anaKelime: "FONDÖTEN", yasakliKelimeler: ["MAKYAJ","SÜRMEK","YÜZ","KAPATICI","PUDRA"]),
  TabuKart(anaKelime: "TEDBİRLİ", yasakliKelimeler: ["ÖNLEMEK","HAZIRLIKLI","ALMAK","ÖNCE","DÜŞÜNMEK"]),
  TabuKart(anaKelime: "ÇAKIŞMAK", yasakliKelimeler: ["ÜST ÜSTE","AYNI","ZAMAN","DENK GELMEK","KESİŞMEK"]),
  TabuKart(anaKelime: "IZGARA", yasakliKelimeler: ["MANGAL","PİŞİRMEK","ET","TAVUK","BARBEKÜ"]),
  TabuKart(anaKelime: "FENG SHUI", yasakliKelimeler: ["DEKORASYON","TARZ","UZAK DOĞU","MEKAN","EV"]),
  TabuKart(anaKelime: "ORHAN PAMUK", yasakliKelimeler: ["ROMAN","NOBEL","YAZAR","BENİM ADIM KIRMIZI","MASUMİYET MÜZESİ"]),
  TabuKart(anaKelime: "HOROZLANMAK", yasakliKelimeler: ["DAYILANMAK","KAFA TUTMAK","DİKLEŞMEK","KAVGA","CESARET"]),
  TabuKart(anaKelime: "MEKİK ÇEKMEK", yasakliKelimeler: ["KARIN KASI","EGZERSİZ","GÖBEK","SPOR","ŞINAV ÇEKMEK"]),
  TabuKart(anaKelime: "OYUN HAVASI", yasakliKelimeler: ["GÖBEK","DANS ETMEK","ORYANTAL","MÜZİK","EĞLENMEK"]),
  TabuKart(anaKelime: "ELİ SIKI", yasakliKelimeler: ["CİMRİ","PARA","HARCAMAK","BİRİKTİRMEK","TUTUMLU"]),
  TabuKart(anaKelime: "GIDIK", yasakliKelimeler: ["ÖPMEK","BEBEK","ÇENE","GERDAN","ŞİŞMAN"]),
  TabuKart(anaKelime: "YETİNMEK", yasakliKelimeler: ["AZ","ÇOK","İSTEMEK","İDARE ETMEK","SAHİP OLMAK"]),
  TabuKart(anaKelime: "MAGMA", yasakliKelimeler: ["YER ALTI","VOLKAN","ERİMEK","YANARDAĞ","LAV"]),
  TabuKart(anaKelime: "KÖÇEK", yasakliKelimeler: ["DANSÖZ","ORYANTAL","OYNAMAK","DÜĞÜN","ERKEK"]),
  TabuKart(anaKelime: "JACK SPARROW", yasakliKelimeler: ["JOHNY DEPP","KARAYİP","KORSAN","KAPTAN","FİLM"]),
  TabuKart(anaKelime: "KISITLI", yasakliKelimeler: ["İMKAN","AZ","SINIRLI","YOKLUK","OLANAK"]),
  TabuKart(anaKelime: "NEJAT İŞLER", yasakliKelimeler: ["AKTÖR","SİNEMA","DİZİ","BARDA","TELEVİZYON"]),
  TabuKart(anaKelime: "PAÇANGA BÖREĞİ", yasakliKelimeler: ["PASTIRMA","MEYHANE","MEZE","YEMEK","ARA SICAK"]),
  TabuKart(anaKelime: "RİMEL", yasakliKelimeler: ["GÖZ","MAKYAJ","KADIN","SÜRMEK","KİRPİK"]),
  TabuKart(anaKelime: "KÜÇÜK DÜŞÜRMEK", yasakliKelimeler: ["DALGA GEÇMEK","GÜLMEK","ALAY","AŞAĞILAMAK","UTANDIRMAK"]),
  TabuKart(anaKelime: "HOVARDA", yasakliKelimeler: ["ÇAPKIN","SEVGİLİ","GECE","PARA HARCAMAK","GÖNÜL"]),
  TabuKart(anaKelime: "TEFLON", yasakliKelimeler: ["EMAYE","TAVA","YAPIŞMAK","ÇELİK","ÇİZMEK"]),
  TabuKart(anaKelime: "AVUÇ", yasakliKelimeler: ["EL","AÇMAK","DİLENCİ","FAL","AYA"]),
  TabuKart(anaKelime: "DAYANIKLI", yasakliKelimeler: ["EŞYA","SAĞLAM","KIRILMAK","BOZULMAK","TÜKETİM"]),
  TabuKart(anaKelime: "AVUCUNU YALAMAK", yasakliKelimeler: ["ALMAK","KALMAK","KAYBETMEK","İSTEMEK","BİTMEK"]),
  TabuKart(anaKelime: "UZANMAK", yasakliKelimeler: ["YORGUN","HASTA","YATMAK","TV","DİNLENMEK"]),
  TabuKart(anaKelime: "ENDAMLI", yasakliKelimeler: ["UZUN","GÖSTERİŞLİ","BOYLU POSLU","GÜZEL","ZARAFET"]),
  TabuKart(anaKelime: "NEON", yasakliKelimeler: ["IŞIK","TABELA","RENKLİ","LAMBA","GAZ"]),
  TabuKart(anaKelime: "BANLİYÖ", yasakliKelimeler: ["TAŞRA","MERKEZ","UZAK","OTURMAK","TREN"]),
  TabuKart(anaKelime: "SAF KAN", yasakliKelimeler: ["AT","CİNS","IRK","ÖZELLİK","KARIŞMAK"]),
  TabuKart(anaKelime: "İPUCU", yasakliKelimeler: ["DEDEKTİF","POLİS","ÇÖZMEK","DELİL","ARAMAK"]),
  TabuKart(anaKelime: "KÜRE", yasakliKelimeler: ["DAİRE","FAL","DÜNYA","YUVARLAK","ŞEKİL"]),
  TabuKart(anaKelime: "SAĞANAK", yasakliKelimeler: ["YAĞMUR","HAVA","KAR","BULUT","ŞEMSİYE"]),
  TabuKart(anaKelime: "LEHÇE", yasakliKelimeler: ["DİL","KONUŞMAK","ŞİVE","AĞIZ","FARKLI"]),
  TabuKart(anaKelime: "BAHSE GİRMEK", yasakliKelimeler: ["İDDİA","AT YARIŞI","MAÇ","PARA","KUMAR"]),
  TabuKart(anaKelime: "MAMA SANDALYESİ", yasakliKelimeler: ["BEBEK","YEMEK","OTURMAK","YÜKSEK","ÇOCUK"]),
  TabuKart(anaKelime: "TAARRUZ", yasakliKelimeler: ["SALDIRI","ESKİ","SAVAŞ","EMRİ","HÜCUM"]),
  TabuKart(anaKelime: "KULAK ZARI", yasakliKelimeler: ["ORGAN","DUYMAK","PATLAMAK","YÜZ","BURUN"]),
  TabuKart(anaKelime: "HIMBIL", yasakliKelimeler: ["YAVAŞ","TEMBEL","UYUŞUK","HAREKET","ŞİŞMAN"]),
  TabuKart(anaKelime: "REKABET", yasakliKelimeler: ["HIRS","ÇEKİŞME","YARIŞMA","RAKİP","SPOR"]),
  TabuKart(anaKelime: "FEMİNİST", yasakliKelimeler: ["KADIN","HAK","SAVUNMAK","EŞİTLİK","HAREKET"]),
  TabuKart(anaKelime: "ENDOSKOPİ", yasakliKelimeler: ["AĞIZ","KAMERA","MİDE","BORU","SOKMAK"]),
  TabuKart(anaKelime: "MİMİK", yasakliKelimeler: ["YÜZ","ANLATMAK","İFADE","HAREKET","DUYGU"]),
  TabuKart(anaKelime: "AFYON", yasakliKelimeler: ["ŞEHİR","SUCUK","HAŞHAŞ","KAYMAK","PATLAMAK"]),
  TabuKart(anaKelime: "NAİF", yasakliKelimeler: ["SAF","HASSAS","DUYGUSAL","MASUM","İYİ NİYETLİ"]),
  TabuKart(anaKelime: "KARBONHİDRAT", yasakliKelimeler: ["KALORİ","EKMEK","DİYET","MAKARNA","PROTEİN"]),
  TabuKart(anaKelime: "SENDROM", yasakliKelimeler: ["BELİRTİ","HASTALIK","BUNALIM","PAZARTESİ","SIKINTI"]),
  TabuKart(anaKelime: "KİNAYE", yasakliKelimeler: ["İĞNELEME","DOLAYLI","İMA ETME","ÜSTÜ KAPALI","LAF DOKUNDURMAK"]),
  TabuKart(anaKelime: "ÇİZMEYİ AŞMAK", yasakliKelimeler: ["İLERİ GİTMEK","HADDİNİ AŞMAK","SINIR","BİLMEK","ÇİZGİ"]),
  TabuKart(anaKelime: "TAVUKGÖĞSÜ", yasakliKelimeler: ["TATLI","SÜT","MUHALLEBİ","KAZANDİBİ","YEMEK"]),
  TabuKart(anaKelime: "BUZ DAĞI", yasakliKelimeler: ["ICEBERG","TİTANİK","KUTUP","DENİZ","SOĞUK"]),
  TabuKart(anaKelime: "DİSKO", yasakliKelimeler: ["DANS","MÜZİK","EĞLENMEK","GECE","KULÜP"]),
  TabuKart(anaKelime: "YENİYETME", yasakliKelimeler: ["ÇOCUK","DELİKANLI","YAŞLI","GENÇ","YETİŞKİN"]),
  TabuKart(anaKelime: "HORON", yasakliKelimeler: ["KARADENİZ","LAZ","TULUM","TEPMEK","HALK OYUNU"]),
  TabuKart(anaKelime: "MÜLAKAT", yasakliKelimeler: ["SORU SORMAK","GÖRÜŞME","İŞE ALMAK","RÖPORTAJ","ÖZGEÇMİŞ"]),
  TabuKart(anaKelime: "PİŞMANİYE", yasakliKelimeler: ["YİYECEK","TEL TEL","TATLI","İZMİT","YOLCULUK"]),
  TabuKart(anaKelime: "İMA ETMEK", yasakliKelimeler: ["DOKUNDURMAK","DOĞRUDAN","DOLAYLI","SEZDİRMEK","SÖYLEMEK"]),
  TabuKart(anaKelime: "STRAPLEZ", yasakliKelimeler: ["BLUZ","ÜST","ASKI","OMUZ","DEKOLTE"]),
  TabuKart(anaKelime: "AĞIR AKSAK", yasakliKelimeler: ["YAVAŞ","DÜZENSİZ","HIZLI","DÖRTNALA","İLERLEMEK"]),
  TabuKart(anaKelime: "ISMARLAMAK", yasakliKelimeler: ["İSTEMEK","PARA","YEMEK","SİPARİŞ","ÖDEMEK"]),
  TabuKart(anaKelime: "YALAP ŞAP", yasakliKelimeler: ["ÜSTÜNKÖRÜ","GELİŞİGÜZEL","TEMİZLİK","İŞ","CEVAPLAMAK"]),
  TabuKart(anaKelime: "ZONKLAMAK", yasakliKelimeler: ["BAŞ AĞRISI","VURMAK","AĞRIMAK","ŞAKAK","BEYİN"]),
  TabuKart(anaKelime: "KRİZ MASASI", yasakliKelimeler: ["BELEDİYE","KURUL","FELAKET","DEPREM","OLUŞTURMAK"]),
  TabuKart(anaKelime: "YIL DÖNÜMÜ", yasakliKelimeler: ["KUTLAMA","EVLİLİK","ÖLÜM","GÜN","KURULUŞ"]),
  TabuKart(anaKelime: "TANRI MİSAFİRİ", yasakliKelimeler: ["KONUK","EV","GELMEK","BEKLEMEK","ANİDEN"]),
  TabuKart(anaKelime: "MAHCUP", yasakliKelimeler: ["ÇEKİNGEN","UTANGAÇ","GÜVENSİZ","RAHAT","GİRİŞKEN"]),
  TabuKart(anaKelime: "ALAKART MÖNÜ", yasakliKelimeler: ["AÇIK BÜFE","FİKS MÖNÜ","SEÇMEK","RESTORAN","YEMEK"]),
  TabuKart(anaKelime: "KAMAROT", yasakliKelimeler: ["GEMİ","YOLCU","SERVİS","GÖREVLİ","KAPTAN"]),
  TabuKart(anaKelime: "JÖN TÜRKLER", yasakliKelimeler: ["OSMANLI","MEŞRUTİYET","AYDIN","TOPLULUK","İTTİHAT VE TERAKKİ"]),
  TabuKart(anaKelime: "EĞİK", yasakliKelimeler: ["DÜZ","ÇİZGİ","DİK","YAMUK","DURMAK"]),
  TabuKart(anaKelime: "SLOGAN", yasakliKelimeler: ["ATMAK","MİTİNG","PARTİ","PROPAGANDA","SÖZ"]),
  TabuKart(anaKelime: "KAFA TUTMAK", yasakliKelimeler: ["KAVGA ETMEK","TARTIŞMAK","KARŞI GELMEK","BOYUN EĞMEK","DİKLENMEK"]),
  TabuKart(anaKelime: "BOĞA", yasakliKelimeler: ["HAYVAN","KIRMIZI","MATADOR","BURÇ","İSPANYA"]),
  TabuKart(anaKelime: "PASKALYA", yasakliKelimeler: ["BAHAR","ÇÖREK","YUMURTA","HRİSTİYAN","BAYRAM"]),
  TabuKart(anaKelime: "ABSÜRT", yasakliKelimeler: ["SAÇMA","KOMEDİ","UYUMSUZ","TUTARSIZ","FİLM"]),
  TabuKart(anaKelime: "ATEŞKES", yasakliKelimeler: ["SAVAŞ","BARIŞ","BİTİRMEK","TESLİM OLMAK","ANLAŞMAK"]),
  TabuKart(anaKelime: "KÖSE", yasakliKelimeler: ["KILSIZ","BIYIK","SAKAL","TÜY","TRAŞ"]),
  TabuKart(anaKelime: "AĞAÇKAKAN", yasakliKelimeler: ["HAYVAN","KUŞ","GAGA","OYMAK","DELMEK"]),
  TabuKart(anaKelime: "KITLAMA", yasakliKelimeler: ["ÇAY","İÇMEK","ŞEKER","ISIRMAK","ERZURUM"]),
  TabuKart(anaKelime: "REST ÇEKMEK", yasakliKelimeler: ["POKER","HEPSİ","PARA","SON VERMEK","KARŞI ÇIKMAK"]),
  TabuKart(anaKelime: "KONTRBAS", yasakliKelimeler: ["ENSTRÜMAN","MÜZİK","ALET","KEMAN","YAYLI"]),
  TabuKart(anaKelime: "WOLVERINE", yasakliKelimeler: ["KURT ADAM","PENÇE","X-MEN","MUTASYON","MARVEL"]),
  TabuKart(anaKelime: "RACON", yasakliKelimeler: ["KESMEK","KABADAYI","ARGO","FİYAKA","DELİKANLI"]),
  TabuKart(anaKelime: "TIRSMAK", yasakliKelimeler: ["KORKMAK","ÇEKİNMEK","ÜRKMEK","CESARET","BIRAKMAK"]),
  TabuKart(anaKelime: "BONO", yasakliKelimeler: ["U2","SOLİST","TAHVİL","KAĞIT","HİSSE SENEDİ"]),
  TabuKart(anaKelime: "GEORGE LUCAS", yasakliKelimeler: ["YÖNETMEN","SİNEMA","STAR WARS","INDIANA JONES","FİLM"]),
  TabuKart(anaKelime: "KOLAÇAN ETMEK", yasakliKelimeler: ["DEVRİYE","DOLAŞMAK","ETRAF","BAKMAK","KONTROL"]),
  TabuKart(anaKelime: "ZULA", yasakliKelimeler: ["SAKLAMAK","GİZLİ","KOYMAK","KAÇAK","MAL"]),
  TabuKart(anaKelime: "LİNYİT", yasakliKelimeler: ["KÖMÜR","MADEN","ZONGULDAK","SOBA","YANMAN"]),
  TabuKart(anaKelime: "İHTİMAL", yasakliKelimeler: ["BELKİ","OLASI","VERMEMEK","OLMAK","UMUT"]),
  TabuKart(anaKelime: "EFOR", yasakliKelimeler: ["GÜÇ","ÇABA","HARCAMAK","KALP","TEST"]),
  TabuKart(anaKelime: "DOLAP BEYGİRİ", yasakliKelimeler: ["DÖNMEK","BAĞLAMAK","AT","EŞEK","SÜREKLİ"]),
  TabuKart(anaKelime: "BUFALO", yasakliKelimeler: ["SIĞIR","AMERİKA","SÜRÜ","KOVBOY","BİZON"]),
  TabuKart(anaKelime: "SIĞINAK", yasakliKelimeler: ["SAVAŞ","BOMBA","SAKLANMAK","KAÇMAK","YER ALTI"]),
  TabuKart(anaKelime: "ALYANS", yasakliKelimeler: ["EVLİLİK","YÜZÜK","KARI-KOCA","PARMAK","TAKMAK"]),
  TabuKart(anaKelime: "ALKOLİK", yasakliKelimeler: ["İÇKİ","GÜN","AYYAŞ","ALIŞKANLIK","BAĞIMLI"]),
  TabuKart(anaKelime: "ATARİ", yasakliKelimeler: ["BİLGİSAYAR","ESKİ","OYUN","BASİT","PROGRAM"]),
  TabuKart(anaKelime: "MAYTAP", yasakliKelimeler: ["IŞIK","KIVILCIM","PASTA","DOĞUM GÜNÜ","YAKMAK"]),
  TabuKart(anaKelime: "İŞARET DİLİ", yasakliKelimeler: ["SAĞIR","KONUŞMAK","EL","HAREKET","İLETİŞİM"]),
  TabuKart(anaKelime: "TAHTAKALE", yasakliKelimeler: ["İSTANBUL","ALIŞVERİŞ","ÇARŞI","UCUZ","EMİNÖNÜ"]),
  TabuKart(anaKelime: "RÖNTGENCİ", yasakliKelimeler: ["DİKİZ","GÖZETLEMEK","SAPIK","GİZLİ","BAKMAK"]),
  TabuKart(anaKelime: "KEMAL SUNAL", yasakliKelimeler: ["SİNEMA","KOMİK","OYUNCU","HABABAM SINIFI","İNEK ŞABAN"]),
  TabuKart(anaKelime: "GÖRGÜ TANIĞI", yasakliKelimeler: ["DELİL","OLAY","MAHKEME","ÇAĞIRMAK","CİNAYET"]),
  TabuKart(anaKelime: "ULAK", yasakliKelimeler: ["HABER","TAŞIMAK","GÖTÜRMEK","POSTACI","AT"]),
  TabuKart(anaKelime: "PÖTİBÖR", yasakliKelimeler: ["BİSKÜVİ","DİKDÖRTGEN","ÇAY","TATLI","KURABİYE"]),
  TabuKart(anaKelime: "KAÇIN KURASI", yasakliKelimeler: ["GÖRMEK","GEÇİRMEK","ALDANMAK","UYANIK","TECRÜBELİ"]),
  TabuKart(anaKelime: "ZIMBA", yasakliKelimeler: ["TUTTURMAK","KIRTASİYE","TEL","DELGEÇ","KAĞIT"]),
  TabuKart(anaKelime: "PASPAL", yasakliKelimeler: ["KOKOŞ","DAĞINIK","BAKIMSIZ","ŞIK","GİYİNMEK"]),
  TabuKart(anaKelime: "ÇİZME", yasakliKelimeler: ["AYAKKABI","UZUN","KADIN","ETEK","BOT"]),
  TabuKart(anaKelime: "DİDİKLEMEK", yasakliKelimeler: ["İNCELEMEK","ARAMAK","DETAY","SORUŞTURMAK","PARÇALAMAK"]),
  TabuKart(anaKelime: "PİYAZ", yasakliKelimeler: ["SALATA","KÖFTE","KURU FASULYE","HAŞLAMAK","SOĞAN"]),
  TabuKart(anaKelime: "TOMBALA", yasakliKelimeler: ["YILBAŞI","OYUN","ÇİNKO","ÇEKMEK","KART"]),
  TabuKart(anaKelime: "METRES", yasakliKelimeler: ["KARI-KOCA","EVLİ","ALDATMAK","YASAK","İLİŞKİ"]),
  TabuKart(anaKelime: "KISA FİLM", yasakliKelimeler: ["SİNEMA","UZUN","FESTİVAL","DAKİKA","YÖNETMEN"]),
  TabuKart(anaKelime: "ÇİFT KAŞARLI", yasakliKelimeler: ["TOST","YEMEK","PEYNİR","UZAMAK","SUCUK"]),
  TabuKart(anaKelime: "KOSTA RİKA", yasakliKelimeler: ["ÜLKE","AMERİKA","ORTA","PANAMA","OKYANUS"]),
  TabuKart(anaKelime: "DAZLAK", yasakliKelimeler: ["KEL","SAÇ","DÖKÜLMEK","NEO-NAZİ","KAZITMAK"]),
  TabuKart(anaKelime: "LODOS", yasakliKelimeler: ["RÜZGAR","POYRAZ","ESMEK","DENİZ","KARAYEL"]),
  TabuKart(anaKelime: "TAC MAHAL", yasakliKelimeler: ["HİNDİSTAN","TARİHİ","SARAY","BİNA","KUBBE"]),
  TabuKart(anaKelime: "KOLAJ", yasakliKelimeler: ["RESİM","BİRLEŞTİRMEK","KAĞIT","KESMEK","YAPIŞTIRMAK"]),
  TabuKart(anaKelime: "MANAVGAT ŞELALESİ", yasakliKelimeler: ["DÖKÜLMEK","ANTALYA","SU","AKMAK","NEHİR"]),
  TabuKart(anaKelime: "ANTONI GAUDI", yasakliKelimeler: ["MİMAR","İSPANYA","BARCELONA","SAGRADA FAMILIA","TASARIM"]),
  TabuKart(anaKelime: "KEKLİK", yasakliKelimeler: ["HAYVAN","KUŞ","AVLAMAK","GÜVERCİN","VURMAK"]),
  TabuKart(anaKelime: "ERZAK", yasakliKelimeler: ["YİYECEK","YOLCULUK","SAKLAMAK","KONSERVE","KİLER"]),
  TabuKart(anaKelime: "TANTANA", yasakliKelimeler: ["ŞAMATA","GÜRÜLTÜ","OLAY","GÖRKEMLİ","ŞAŞAALI"]),
  TabuKart(anaKelime: "SELEKTÖR", yasakliKelimeler: ["ARABA","FAR","IŞIK","YAKMAK","UYARMAK"]),
  TabuKart(anaKelime: "ALIN TERİ", yasakliKelimeler: ["ÇALIŞMAK","EMEK","DÖKMEK","ZAHMET","UĞRAŞMAK"]),
  TabuKart(anaKelime: "ADAM ASMACA", yasakliKelimeler: ["OYUN","KELİME","BULMAK","ÇİZMEK","HARF"]),
  TabuKart(anaKelime: "SEMİNER", yasakliKelimeler: ["KONUŞMA","SUNUM","KONFERANS","EĞİTİM","TOPLANTI"]),
  TabuKart(anaKelime: "ELİPS", yasakliKelimeler: ["ŞEKİL","YUVARLAK","DAİRE","DÜNYA","ÇEMBER"]),
  TabuKart(anaKelime: "BASAMAK", yasakliKelimeler: ["MERDİVEN","ÇIKMAK","ASANSÖR","KULLANMAK","AŞAMA"]),
  TabuKart(anaKelime: "KAVŞAK", yasakliKelimeler: ["DÖRT YOL","ARABA","KESİŞMEK","BİRLEŞMEK","DÖNMEK"]),
  TabuKart(anaKelime: "ALTYAZI", yasakliKelimeler: ["SİNEMA","ÇEVİRİ","FİLM","DUBLAJ","İNGİLİZCE"]),
  TabuKart(anaKelime: "ALATURKA", yasakliKelimeler: ["ALAFRANGA","MÜZİK","ESKİ","GELENEK","TUVALET"]),
  TabuKart(anaKelime: "KANAVİÇE", yasakliKelimeler: ["ELİŞİ","KASNAK","İPLİK","İĞNE","BEZ"]),
  TabuKart(anaKelime: "DİSPANSER", yasakliKelimeler: ["HASTANE","DOKTOR","VEREM","SAĞLIK OCAĞI","POLİKLİNİK"]),
  TabuKart(anaKelime: "CİNSİYET", yasakliKelimeler: ["KADIN","ERKEK","DİŞİ","DOĞMAK","KİMLİK"]),
  TabuKart(anaKelime: "LORD", yasakliKelimeler: ["LEYDİ","BARON","UNVAN","İNGİLTERE","ASALET"]),
  TabuKart(anaKelime: "REZERV", yasakliKelimeler: ["PETROL","SAKLAMAK","YEDEK","BİRİKTİRMEK","DÖVİZ"]),
  TabuKart(anaKelime: "VİCDAN AZABI", yasakliKelimeler: ["ÇEKMEK","DUYMAK","ÜZÜLMEK","ACI","KÖTÜ"]),
  TabuKart(anaKelime: "DOMİNO", yasakliKelimeler: ["TAŞ","OYUN","DEVİRMEK","DİKDÖRTGEN","NOKTA"]),
  TabuKart(anaKelime: "PİLATES", yasakliKelimeler: ["SPOR","EGZERSİZ","TOP","YOGA","ESNETMEK"]),
  TabuKart(anaKelime: "ZIRH", yasakliKelimeler: ["ŞÖVALYE","KORUMAK","SAVAŞ","METAL","GİYMEK"]),
  TabuKart(anaKelime: "GO-KART", yasakliKelimeler: ["KÜCHÜK","FORMULA 1","MOTOR","YARIŞ","PİST"]),
  TabuKart(anaKelime: "SABAN", yasakliKelimeler: ["TARLA","SÜRMEK","ÇİFTÇİ","TARIM","HAYVAN"]),
  TabuKart(anaKelime: "KAVUK", yasakliKelimeler: ["OSMANLI","SARIK","BAŞLIK","ŞAPKA","PADİŞAH"]),
  TabuKart(anaKelime: "TIRIS", yasakliKelimeler: ["AT","YÜRÜMEK","DÖRTNALA","HIZLI","VIZ GELMEK"]),
  TabuKart(anaKelime: "GICIRTI", yasakliKelimeler: ["SES","KAPI","YAĞLAMAK","TAHTA","PAS"]),
  TabuKart(anaKelime: "KONFORLU", yasakliKelimeler: ["RAHAT","DÖŞEMEK","MOBİLYA","OTEL","EV"]),
  TabuKart(anaKelime: "AŞAĞI YUKARI", yasakliKelimeler: ["YAKLAŞIK","TAHMİNİ","TAM","İNMEK","ÇIKMAK"]),
TabuKart(anaKelime: "GO-KART", yasakliKelimeler: ["KÜÇÜK","FORMULA 1","MOTOR","YARIŞ","PİST"]),
  TabuKart(anaKelime: "SABAN", yasakliKelimeler: ["TARLA","SÜRMEK","ÇİFTÇİ","TARIM","HAYVAN"]),
  TabuKart(anaKelime: "KAVUK", yasakliKelimeler: ["OSMANLI","SARIK","BAŞLIK","ŞAPKA","PADİŞAH"]),
  TabuKart(anaKelime: "TIRIS", yasakliKelimeler: ["AT","YÜRÜMEK","DÖRTNALA","HIZLI","VIZ GELMEK"]),
  TabuKart(anaKelime: "GICIRTI", yasakliKelimeler: ["SES","KAPI","YAĞLAMAK","TAHTA","PAS"]),
  TabuKart(anaKelime: "KONFORLU", yasakliKelimeler: ["RAHAT","DÖŞEMEK","MOBİLYA","OTEL","EV"]),
  TabuKart(anaKelime: "AŞAĞI YUKARI", yasakliKelimeler: ["YAKLAŞIK","TAHMİNİ","TAM","İNMEK","ÇIKMAK"]),
  TabuKart(anaKelime: "BAĞLANTI", yasakliKelimeler: ["İLETİŞİM", "MESAJ", "DİL", "KONUŞMAK", "İNTERNET"]), //
  TabuKart(anaKelime: "DÜŞÜNMEK", yasakliKelimeler: ["AKIL", "FİKİR", "ZİHİN", "KARAR", "HAYAL"]), //
  TabuKart(anaKelime: "RÜYA", yasakliKelimeler: ["UYKU", "HAYAL", "GECE", "GÖRMEK", "DÜŞ"]), //
  TabuKart(anaKelime: "YORGUN", yasakliKelimeler: ["UYKU", "HALSİZ", "BİTKİN", "DİNLENMEK", "GÜN"]), //
  TabuKart(anaKelime: "KADRAJ", yasakliKelimeler: ["FOTOĞRAF", "KAMERA", "GÖRÜNTÜ", "ÇERÇEVE", "BAKMAK"]),
  TabuKart(anaKelime: "KOMPANSASYON", yasakliKelimeler: ["ELEKTRİK", "GÜÇ", "DENGE", "MÜHENDİS", "PANEL"]),
  TabuKart(anaKelime: "MUŞ ALPARSLAN", yasakliKelimeler: ["ÜNİVERSİTE", "KAMPÜS", "LALE", "EĞİTİM", "ŞEHİR"]),
  TabuKart(anaKelime: "KODLAMA", yasakliKelimeler: ["YAZILIM", "BİLGİSAYAR", "PROGRAM", "DART", "GELİŞTİRİCİ"]),
  TabuKart(anaKelime: "SİBER GÜVENLİK", yasakliKelimeler: ["HACKER", "KORUMA", "ŞİFRE", "VERİ", "SALDIRI"]),
  TabuKart(anaKelime: "VERİTABANI", yasakliKelimeler: ["SQL", "KAYIT", "BİLGİ", "DEPOLAMA", "SİSTEM"]),
  TabuKart(anaKelime: "YAPAY ZEKA", yasakliKelimeler: ["CHATGPT", "ROBOT", "ÖĞRENME", "GELECEK", "AKILLI"]),
];